export interface RshsRoomItem {
  id: string;
  number: string;
  type: string;
  price: number;
  status: string;
  floor: number;
  size?: string;
  bedType?: string;
  electricity?: string;
  view?: string;
  capacity?: string;
  videoUrl?: string;
  gallery?: string[];
  facilities?: string[];
  categorizedFacilities?: {
    kamar: string[];
    kamarMandi: string[];
    smart: string[];
    bersama: string[];
  };
  imageUrl?: string | null;
}

export const RSHS_ROOMS_DATA: RshsRoomItem[] = [
  {
    id: 'rshs-eksekutif',
    number: 'EKS-01',
    type: 'Eksekutif',
    price: 1500000,
    status: 'AVAILABLE',
    floor: 1,
    size: '4 x 4.5 m (18 m²)',
    bedType: 'Kasur Comfort Max 2 Org',
    electricity: 'Listrik & Air Termasuk',
    view: 'Area Tenang & Nyaman',
    capacity: 'Max 2 Orang (Total 6 Kamar)',
    videoUrl: 'https://www.youtube.com/embed/YWBWxMWL52I',
    imageUrl: '/images/rshs/Eksekutif/1.png',
    gallery: [
      '/images/rshs/Eksekutif/1.png',
      '/images/rshs/Eksekutif/2.png',
      '/images/rshs/Eksekutif/3.png',
      '/images/rshs/Eksekutif/4.png',
      '/images/rshs/Eksekutif/5.png',
      '/images/rshs/Eksekutif/6.png',
      '/images/rshs/Eksekutif/7.png',
      '/images/rshs/Eksekutif/8.png',
    ],
    facilities: [
      'Kasur Comfort',
      'Lemari & Meja Kursi',
      'Kipas Angin',
      'Kamar Mandi Dalam',
      'Free Laundry 5 kg / bln',
      'Mini Gym & CCTV',
      'Dapur & Kulkas Bersama',
      'Pembersihan Kamar & Sprei 2 Minggu Sekali',
      'Air Mineral & Alat Solat',
      'Listrik, Air, WiFi & Parkir',
    ],
    categorizedFacilities: {
      kamar: ['Kasur Comfort Luas', 'Lemari Pakaian', 'Meja & Kursi Kerja', 'Kipas Angin', 'Alat Solat', 'Pembersihan Kamar 2 Minggu Sekali'],
      kamarMandi: ['Kamar Mandi Dalam Pribadi', 'Shower', 'Air Lancar'],
      smart: ['WiFi Kencang', 'CCTV Keamanan 24 Jam'],
      bersama: ['Mini Gym Olahraga', 'Dapur Bersama + Alat Masak & Makan', 'Kulkas Bersama', 'Ruang Terbuka Bersama', 'Laundry Room (Mesin Cuci, Setrika, Hanger)', 'Parkir Motor'],
    },
  },
  {
    id: 'rshs-nyaman',
    number: 'NYM-01',
    type: 'Nyaman',
    price: 1000000,
    status: 'AVAILABLE',
    floor: 1,
    size: '3.5 x 4 m (14 m²)',
    bedType: 'Single Comfort',
    electricity: 'Termasuk',
    view: 'Area Kosan RSHS',
    capacity: '1 Orang (Total 8 Kamar)',
    videoUrl: 'https://www.youtube.com/embed/CmL0OUHmGAQ',
    imageUrl: '/images/rshs/Nyaman/1.png',
    gallery: [
      '/images/rshs/Nyaman/1.png',
      '/images/rshs/Nyaman/2.png',
      '/images/rshs/Nyaman/3.png',
      '/images/rshs/Nyaman/4.png',
      '/images/rshs/Nyaman/5.png',
      '/images/rshs/Nyaman/6.png',
      '/images/rshs/Nyaman/7.png',
      '/images/rshs/Nyaman/8.png',
    ],
    facilities: [
      'Kipas Angin',
      'Laundry Room',
      'Free Laundry 5 kg / bln',
      'Parkir Motor',
      'Dapur Bersama',
      'CCTV Keamanan',
    ],
    categorizedFacilities: {
      kamar: ['Kipas Angin', 'Kasur Single Comfort', 'Lemari Pakaian'],
      kamarMandi: ['Kamar Mandi Bersih', 'Air Lancar'],
      smart: ['CCTV Keamanan 24 Jam', 'WiFi'],
      bersama: ['Laundry Room', 'Free Laundry 5 kg / bln', 'Dapur Bersama', 'Parkir Motor Luas'],
    },
  },
  {
    id: 'rshs-nyaman-2',
    number: 'NYM-02',
    type: 'Nyaman 2',
    price: 1400000,
    status: 'AVAILABLE',
    floor: 2,
    size: '4 x 4 m (16 m²)',
    bedType: 'Kasur Comfort',
    electricity: 'Termasuk',
    view: 'Area Tenang',
    capacity: '1 - 2 Orang (Total 6 Kamar)',
    videoUrl: 'https://www.youtube.com/embed/YWBWxMWL52I',
    imageUrl: '/images/rshs/Nyaman%202/1.png',
    gallery: [
      '/images/rshs/Nyaman%202/1.png',
      '/images/rshs/Nyaman%202/2.png',
      '/images/rshs/Nyaman%202/3.png',
      '/images/rshs/Nyaman%202/4.png',
    ],
    facilities: [
      'Kasur & Lemari',
      'Meja Kerja',
      'Kipas Angin',
      'Kamar Mandi Dalam',
      'Closet Duduk & Shower',
      'Dapur Bersama & Alat Masak',
      'Kulkas Bersama',
      'Mesin Cuci Bersama & Laundry Room',
      'Free Laundry 5 kg',
      'Pembersihan Kamar 2 Minggu Sekali',
      'Air Mineral & Listrik',
      'WiFi & CCTV',
    ],
    categorizedFacilities: {
      kamar: ['Kasur Comfort', 'Lemari Pakaian', 'Meja Kerja', 'Kipas Angin', 'Pembersihan Kamar 2 Minggu Sekali'],
      kamarMandi: ['Kamar Mandi Dalam', 'Closet Duduk', 'Shower Mandi Modern'],
      smart: ['WiFi Kencang', 'CCTV 24 Jam'],
      bersama: ['Dapur Bersama + Alat Masak', 'Kulkas Bersama', 'Mesin Cuci Bersama', 'Laundry Room & Free 5kg'],
    },
  },
  {
    id: 'rshs-nyaman-3',
    number: 'NYM-03',
    type: 'Nyaman 3',
    price: 1300000,
    status: 'AVAILABLE',
    floor: 2,
    size: '3.5 x 4 m (14 m²)',
    bedType: 'Single Bed Comfort',
    electricity: 'Token Awal Terisi',
    view: 'Sirkulasi Udara Alami',
    capacity: '1 Orang (Total 5 Kamar)',
    videoUrl: 'https://www.youtube.com/embed/CmL0OUHmGAQ',
    imageUrl: '/images/rshs/Nyaman%203/1.png',
    gallery: [
      '/images/rshs/Nyaman%203/1.png',
      '/images/rshs/Nyaman%203/2.png',
      '/images/rshs/Nyaman%203/3.png',
      '/images/rshs/Nyaman%203/4.png',
      '/images/rshs/Nyaman%203/5.png',
    ],
    facilities: [
      'Kasur & Lemari',
      'Meja Belajar',
      'Kamar Mandi Dalam',
      'Closet Duduk',
      'Water Heater Air Hangat',
      'Dapur & Kulkas Bersama',
      'Free Laundry 5 kg',
      'Air PDAM & Token Listrik Awal',
      'WiFi',
    ],
    categorizedFacilities: {
      kamar: ['Kasur Single Comfort', 'Lemari Pakaian', 'Meja Belajar'],
      kamarMandi: ['Kamar Mandi Dalam', 'Closet Duduk', 'Water Heater (Air Hangat)'],
      smart: ['WiFi Kencang'],
      bersama: ['Dapur Bersama', 'Kulkas Bersama', 'Free Laundry 5 kg', 'Air PDAM'],
    },
  },
  {
    id: 'rshs-nyaman-4',
    number: 'NYM-04',
    type: 'Nyaman 4',
    price: 1400000,
    status: 'AVAILABLE',
    floor: 3,
    size: '4 x 4.5 m (18 m²)',
    bedType: 'Comfort Bed Max 2 Org',
    electricity: 'Termasuk',
    view: 'Ruang Terbuka Hijau Bersama',
    capacity: 'Max 2 Orang (Total 14 Kamar)',
    videoUrl: 'https://www.youtube.com/embed/r4BsLqEk1LQ',
    imageUrl: '/images/rshs/Nyaman%204/1.png',
    gallery: [
      '/images/rshs/Nyaman%204/1.png',
      '/images/rshs/Nyaman%204/2.png',
      '/images/rshs/Nyaman%204/3.png',
    ],
    facilities: [
      'Kasur & Lemari',
      'Meja Kerja',
      'Kamar Mandi Dalam',
      'Dapur Bersama',
      'Ruang Terbuka Bersama',
      'Laundry Room & Free Laundry 5 kg',
      'Air Mineral & PDAM',
      'Listrik & WiFi',
      'Parkir Motor',
      'Free Trial Oxy Gym',
    ],
    categorizedFacilities: {
      kamar: ['Kasur Nyaman Max 2 Org', 'Lemari Pakaian', 'Meja Kerja'],
      kamarMandi: ['Kamar Mandi Dalam Pribadi', 'Shower Air Bersih PDAM'],
      smart: ['WiFi Kencang'],
      bersama: ['Ruang Terbuka Bersama Luas', 'Dapur Bersama', 'Laundry Room & Free Laundry 5 kg', 'Parkir Motor Aman', 'Bonus Free Trial Oxy Gym'],
    },
  },
  {
    id: 'rshs-paviliun-eksekutif',
    number: 'PV-01',
    type: 'Paviliun Eksekutif',
    price: 2800000,
    status: 'AVAILABLE',
    floor: 1,
    size: '6 x 7 m (42 m²)',
    bedType: 'King Bed + Ruang Tamu',
    electricity: 'Termasuk',
    view: 'Akses Privat Depan',
    capacity: '2 - 3 Orang (Total 2 Unit)',
    videoUrl: 'https://www.youtube.com/embed/YWBWxMWL52I',
    imageUrl: '/images/rshs/Paviliun%20Eksekutif/1.png',
    gallery: [
      '/images/rshs/Paviliun%20Eksekutif/1.png',
      '/images/rshs/Paviliun%20Eksekutif/2.png',
      '/images/rshs/Paviliun%20Eksekutif/3.png',
      '/images/rshs/Paviliun%20Eksekutif/4.png',
      '/images/rshs/Paviliun%20Eksekutif/5.png',
      '/images/rshs/Paviliun%20Eksekutif/6.png',
      '/images/rshs/Paviliun%20Eksekutif/7.png',
      '/images/rshs/Paviliun%20Eksekutif/8.png',
    ],
    facilities: [
      'Ruang Paviliun Luas & Privat',
      'Kasur King Size Comfort',
      'Lemari Pakaian Besar',
      'Meja & Kursi Santai',
      'Kamar Mandi Dalam Luas',
      'Free Laundry 10 kg / bln',
      'Dapur & Kulkas',
      'WiFi & CCTV 24 Jam',
      'Parkir Motor',
    ],
    categorizedFacilities: {
      kamar: ['Unit Paviliun Privat', 'Kasur King Comfort', 'Lemari Besar', 'Meja & Ruang Duduk'],
      kamarMandi: ['Kamar Mandi Dalam Luas', 'Shower & Kloset Duduk'],
      smart: ['WiFi Cepat', 'CCTV 24 Jam'],
      bersama: ['Dapur Privat/Bersama', 'Laundry Room & Free 10kg', 'Parkir Motor'],
    },
  },
  {
    id: 'rshs-paviliun-tipe-b',
    number: 'PV-02',
    type: 'Paviliun Tipe B',
    price: 2600000,
    status: 'AVAILABLE',
    floor: 1,
    size: '5.5 x 6.5 m (36 m²)',
    bedType: '1 Kasur 160x200 + 2 Kasur Single',
    electricity: 'Termasuk',
    view: 'Cocok Pasangan / Kelompok',
    capacity: '2 - 4 Orang (Total 3 Unit)',
    videoUrl: 'https://www.youtube.com/embed/r4BsLqEk1LQ',
    imageUrl: '/images/rshs/Paviliun%20Tipe%20B/1.jpg',
    gallery: [
      '/images/rshs/Paviliun%20Tipe%20B/1.jpg',
      '/images/rshs/Paviliun%20Tipe%20B/2.png',
      '/images/rshs/Paviliun%20Tipe%20B/3.png',
      '/images/rshs/Paviliun%20Tipe%20B/4.png',
      '/images/rshs/Paviliun%20Tipe%20B/5.png',
      '/images/rshs/Paviliun%20Tipe%20B/6.png',
    ],
    facilities: [
      '1 Kasur Ukuran 160 x 200',
      '2 Kasur Single',
      '1 Kamar Mandi Dalam',
      'Closet Duduk',
      'Meja & Lemari Baju Ukuran Besar',
      '1 Kompor Gas & Tabung Gas',
      'Free Laundry 10 kg',
      'Air Mineral & Air Bersih',
      'Listrik & WiFi',
    ],
    categorizedFacilities: {
      kamar: ['1 Kasur Queen 160x200', '2 Kasur Single Tambahan', 'Lemari Baju Ukuran Besar', 'Meja'],
      kamarMandi: ['Kamar Mandi Dalam', 'Closet Duduk', 'Shower'],
      smart: ['WiFi Kencang'],
      bersama: ['1 Kompor Gas Siap Masak + Gas', 'Air Mineral Disediakan', 'Free Laundry 10 kg', 'Listrik Termasuk'],
    },
  },
  {
    id: 'rshs-super-nyaman',
    number: 'SN-01',
    type: 'Super Nyaman',
    price: 1700000,
    status: 'AVAILABLE',
    floor: 2,
    size: '4.5 x 5 m (22 m²)',
    bedType: 'Queen Comfort Bed',
    electricity: 'Termasuk',
    view: 'Area Tenang & Nyaman',
    capacity: '1 - 2 Orang (Total 4 Kamar)',
    videoUrl: 'https://www.youtube.com/embed/YWBWxMWL52I',
    imageUrl: '/images/rshs/Super%20Nyaman/1.png',
    gallery: [
      '/images/rshs/Super%20Nyaman/1.png',
      '/images/rshs/Eksekutif/2.png',
      '/images/rshs/Eksekutif/3.png',
    ],
    facilities: [
      'Kasur Comfort Luas',
      'Lemari & Meja Kerja',
      'Kamar Mandi Dalam',
      'Water Heater Air Hangat',
      'Free Laundry 5 kg / bln',
      'Dapur & Kulkas Bersama',
      'CCTV 24 Jam & WiFi Kencang',
      'Parkir Motor',
    ],
    categorizedFacilities: {
      kamar: ['Kasur Comfort Luas', 'Lemari Pakaian', 'Meja Kerja'],
      kamarMandi: ['Kamar Mandi Dalam', 'Water Heater (Air Hangat)', 'Shower'],
      smart: ['WiFi Kencang', 'CCTV 24 Jam'],
      bersama: ['Dapur Bersama', 'Kulkas Bersama', 'Free Laundry 5 kg / bln', 'Parkir Motor'],
    },
  },
];
